### ISSUE TITLE
A bit faster

### ISSUE THREAD

**Issue by devenv** [whiteinge/dotfiles#12]
Most files I have to merge are pretty straight forward, so I don't need the other tabs.
I changed the script a bit:

```
$cmd -f -R -d "${LCONFL}" "${RCONFL}" \
     -c ":set noro" \
     -c ":nmap <leader>D :tabe $QLOCAL<CR>:vert diffs $QBASE<CR>:vert diffs $QREMOTE<CR>:winct<CR>:tabe $QMERGED<CR>:tabfir"
```

So now if I need the other tabs I just press <leader>D
May be it should be an option or something...

**Comment by whiteinge** [comment]
Sorry for the slow reply! I didn't get a notification email from GitHub for this. ☹️ 

This is a clever change and you're right it's much faster. Thanks for opening this!
