### ISSUE TITLE
wrt  devdocs-local and similar util

### ISSUE THREAD

**Issue by dubiouscript** [whiteinge/dotfiles#15]
https://github.com/whiteinge/dotfiles/blob/9b3650b05fcbb1716bc24206efad4612a57d156f/bin/devdocs-local#L4

i found out about at https://www.eseth.org/2020/devdocs-cli.html 

as yet i have not looked in much depth or run the scripts my self =s, 
however just wanted to mention that it reminded of  (conceptually similar)  dasht :  https://github.com/sunaku/dasht - 'Search API docs offline, in terminal or browser'

thanks for the interesting scripts!

**Comment by whiteinge** [comment]
Thanks for the compliments. Dasht is a cool set of scripts with a much more grand scope than devdocs-local. My script is just a tiny wrapper around extracting part of a JSON file and piping that to lynx, with a fuzzy-finder in between. It does very little by design. :-)
