### ISSUE TITLE
Not an issue but a question

### ISSUE THREAD

**Issue by rachidbch** [whiteinge/dotfiles#17]
Hi @whiteinge,

I'm trying to adapt and use your devdocs-local script. 
Thank you for making it public :+1: 

I find it incredibly difficult to find where you got 'htmlstar' from ...
I would had thought this utility is installed by the 'XMLStarlet' package, but it's not the case.
For information I'm on Ubuntu.

What is strange is that when searching for 'htmlstar' on Google you are litteraly the only person in the world reference it ....
Where do I find it ?

**Comment by whiteinge** [comment]
Oh no! [htmlstar also lives in my dotfiles](https://github.com/whiteinge/dotfiles/blob/master/bin/htmlstar) :stuck_out_tongue_closed_eyes: it's a little wrapper around xmlstarlet to convert html to xhtml. (Tidy can also do that if that's preferable.)

The Devdocs.io folk updated one of the subdomains they use and I just now pushed a fix for that so make sure you grab the latest version of that script again.

Ping me if you run into any trouble.

**Comment by rachidbch** [comment]
Thanks for your answer.

Actually I've spotted yesterday the change in devdocs.io dubdomain dedicated to serving docs.

By the way I've shamelessly stolen your script to adapt it to my needs.

For htmlstar, I ditched the dependency. You don't really need to scrap the list of docs as you can get it on http://devdocs.io/docs.json.

So the `list` function can be as simple as:
`curl -sSL http://devdocs.io/docs.json | jq -r '.[] | [ .slug, .mtime ] | @tsv'`

I also replaced fzy by fzf because that's the one I know and use.

Nathaniel, a big kudo for puting together this script !
I've evaluated a bunch of dash alternative for linux and really your script is the best solution I've found.
The UX is nice: It's intuitive, fast, hackable and beautiful.

(A tend to live in the terminal and don't particularly enjoy full blown apps like zeal)

Thanks !

**Comment by whiteinge** [comment]
That's awesome to hear! I'm happy you could adapt it to your workflow. Thanks for letting me know.
