### ISSUE TITLE
Symbolic Links in /usr/share/zoneinfo

### ISSUE THREAD

**Issue by Knusper** [whiteinge/dotfiles#18]
Hi,

at least on Debian linux, the `/usr/share/zoneinfo` contains many symbolic links.
E.g. Kuwait -> Aden etc. The current `find -type f` in the timezonefzy script misses those.   I now use `find -type f,c`, which is, however, only compatible with GNU find.

Best,
Christian

**Comment by whiteinge** [comment]
Oh, thanks! I usually search for time zone names instead of location/friendly names and didn't realize there's a bunch of useful entries in that directory that are missing in the output. Does the following work for you?
```
find -type f -o -type l
```

**Comment by whiteinge** [comment]
Ooh, or perhaps [this](https://unix.stackexchange.com/a/698068) is better:

```
awk '/^Z/ { print $2 }; /^L/ { print $3 }' /usr/share/zoneinfo/tzdata.zi
```

**Comment by Knusper** [comment]
> Ooh, or perhaps [this](https://unix.stackexchange.com/a/698068) is better:
> 
> ```
> awk '/^Z/ { print $2 }; /^L/ { print $3 }' /usr/share/zoneinfo/tzdata.zi
> ```

On my debian buster box this file is not available, they fixed this in newer debian versions.  The other option works.
