### ISSUE TITLE
pprint.pprint sort dict by key which cerate confution with ordered dicts

### ISSUE THREAD

**Issue by nueces** [whiteinge/dotfiles#23]
https://github.com/whiteinge/dotfiles/blob/72f6d08e827e8067e24db39ef7cea0500695f06c/.pythonrc.py#L95

I been using your pythonrc for many years and wasn't until now that I found this issues, probably because before python 3.7 dictionaries didn't preserve the order and because of that I never pay much attention to that.
```python
>>> d = {'one': 1, 'two': 2, 'three': 3}
>>> print(d)
{'one': 1, 'two': 2, 'three': 3}
>>> pprint.pprint(d)
{'one': 1, 'three': 3, 'two': 2}
```

Anyway thanks for your file.
Cheers.

**Comment by nueces** [comment]
Found the issue in the pprint repo
https://github.com/python/cpython/issues/74855

The solution is quite simple
```python
>>> pprint.pprint(d, sort_dicts=False)
{'one': 1, 'two': 2, 'three': 3}
```

**Comment by whiteinge** [comment]
Awesome. Thanks for filing the issue and linking the fix!
